apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-staging
  namespace: argocd
spec:
  project: unoarena
  destination:
    server: https://kubernetes.default.svc
    namespace: unoarena-staging
  sources:
    - repoURL: https://gitlab.com/itba-73-40-microservicios/alumnos/2026-s1/grupo-4/amicro-tp.git
      targetRevision: main
      path: services/gateway/chart
      helm:
        valueFiles:
          - $values/gitops/apps/gateway/overlays/staging/values.yaml
    - repoURL: https://gitlab.com/itba-73-40-microservicios/alumnos/2026-s1/grupo-4/amicro-tp.git
      targetRevision: main
      ref: values
  syncPolicy:
  automated:
    prune: true
    selfHeal: true
    syncOptions:
      - CreateNamespace=true
