apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: room-gameplay-staging
  namespace: argocd
spec:
  project: unoarena
  destination:
    server: https://kubernetes.default.svc
    namespace: unoarena-staging
  sources:
    - repoURL: REPLACE_REPO_URL
      targetRevision: main
      path: services/room-gameplay/chart
      helm:
        valueFiles:
          - $values/gitops/apps/room-gameplay/overlays/staging/values.yaml
    - repoURL: REPLACE_REPO_URL
      targetRevision: main
      ref: values
  syncPolicy:
  automated:
    prune: true
    selfHeal: true
    syncOptions:
      - CreateNamespace=true
