apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: room-gameplay-production
  namespace: argocd
spec:
  project: unoarena
  destination:
    server: https://kubernetes.default.svc
    namespace: unoarena-production
  sources:
    - repoURL: https://gitlab.com/itba-73-40-microservicios/alumnos/2026-s1/grupo-4/amicro-tp.git
      targetRevision: main
      path: services/room-gameplay/chart
      helm:
        valueFiles:
          - $values/gitops/apps/room-gameplay/overlays/production/values.yaml
    - repoURL: https://gitlab.com/itba-73-40-microservicios/alumnos/2026-s1/grupo-4/amicro-tp.git
      targetRevision: main
      ref: values
  syncPolicy:
  # production: manual sync (no automated block) — promote via gate
    syncOptions:
      - CreateNamespace=true
