#!/usr/bin/env python3
"""Async contract checks for the events one context publishes and another reads.

Demonstrates WHERE contract testing lives in the pipeline (consigna §6.3), and since P5 it checks
real producers rather than illustrative ones. For each contract it does two things:

1. Producer conformance — the sample the producer emits must validate against the published JSON
   Schema. The samples are not written here: each is generated by the producer's own test suite from
   the event class and, for room events, the `publicPayload` privacy filter, then committed under
   samples/. A field renamed in Kotlin changes that file, and this job goes red.
2. Backward compatibility — the fields each consumer depends on must still be required by the
   schema, so a producer-side change cannot silently drop a field a consumer reads.

A failure here blocks build of the affected consumers (cross-service fail-fast).

P7 added the second and third contracts. `MatchCompleted` is the one to look at hardest: the
tournament's whole saga turns on `advancingPlayers`, so dropping it would not degrade a number, it
would stall every bracket in the system with nothing logging an error.
"""
import json
import sys
from pathlib import Path

from jsonschema import Draft202012Validator

HERE = Path(__file__).parent


class Contract:
    def __init__(self, name: str, schema: str, sample: str, producer: str, consumers: dict[str, list[str]]):
        self.name = name
        self.schema = json.loads((HERE / schema).read_text())
        self.sample = HERE / "samples" / sample
        self.producer = producer
        # Fields each CONSUMER reads (must remain required by the schema).
        self.consumers = consumers


CONTRACTS = [
    Contract(
        name="GameCompleted",
        schema="game-completed.schema.json",
        sample="game-completed.json",
        producer="room-gameplay",
        consumers={
            # ranking filters casual, non-abandoned games and scores Elo off the finishing order;
            # analytics-workers key their projections on the room and its position in that room's
            # log; spectator needs only enough to recognise the event and place it in the room's log
            # — this is the terminal signal that tells its projection the game is over.
            "ranking": ["roomType", "isAbandoned", "finishingOrder", "cardPointTotals", "gameNumber"],
            "analytics-workers": ["roomId", "sequenceNumber", "gameNumber", "at"],
            "spectator": ["type", "roomId", "sequenceNumber"],
        },
    ),
    Contract(
        name="MatchCompleted",
        schema="match-completed.schema.json",
        sample="match-completed.json",
        producer="room-gameplay",
        consumers={
            # The saga records a room's verdict against its round. `roomId` is how it finds which
            # round, and `advancingPlayers` is the verdict itself — without either, rounds never
            # complete and the tournament waits for ever.
            "tournament": ["type", "roomId", "advancingPlayers"],
        },
    ),
    Contract(
        name="TournamentCompleted",
        schema="tournament-completed.schema.json",
        sample="tournament-completed.json",
        producer="tournament",
        consumers={
            # ranking turns the final standing into a placement rating; analytics records the same
            # standing as the bracket's placements.
            "ranking": ["type", "tournamentId", "finalPlacements", "at"],
            "analytics-workers": ["tournamentId", "champion", "finalPlacements", "at"],
        },
    ),
]


def check(contract: Contract) -> bool:
    if not contract.sample.exists():
        print(f"FAIL: {contract.sample} is missing — it is generated by {contract.producer}'s test suite.")
        print(f"      Run: CONTRACT_SAMPLE_REGENERATE=1 ./gradlew test  (in services/{contract.producer})")
        return False

    producer_sample = json.loads(contract.sample.read_text())
    errors = sorted(Draft202012Validator(contract.schema).iter_errors(producer_sample), key=str)
    if errors:
        print(f"FAIL: producer sample does not conform to the {contract.name} schema:")
        for error in errors:
            print(f"  - {error.message}")
        return False
    print(f"OK: {contract.producer}'s {contract.name} sample conforms to its schema.")

    required = set(contract.schema.get("required", []))
    ok = True
    for consumer, fields in contract.consumers.items():
        missing = [field for field in fields if field not in required]
        if missing:
            ok = False
            print(f"FAIL: {consumer} depends on {contract.name} fields no longer required: {missing}")
        else:
            print(f"OK: {consumer}'s required {contract.name} fields are all present in the contract.")
    return ok


def main() -> int:
    return 0 if all([check(contract) for contract in CONTRACTS]) else 1


if __name__ == "__main__":
    sys.exit(main())
