#!/usr/bin/env python3
"""Async contract check for the GameCompleted event.

Demonstrates WHERE contract testing lives in the pipeline (consigna §6.3), and since P5 it checks a
real producer rather than an illustrative one. It does two things:

1. Producer conformance — the sample room-gameplay emits must validate against the published JSON
   Schema. The sample is not written here: it is generated by the producer's own test suite from the
   event class and the `publicPayload` privacy filter, and committed under samples/. A field renamed
   in Kotlin changes that file, and this job goes red.
2. Backward compatibility — the fields the consumers (ranking, analytics-workers) depend on must
   still be required by the schema, so a producer-side change cannot silently drop a field a
   consumer reads.

A failure here blocks build of the affected consumers (cross-service fail-fast).
"""
import json
import sys
from pathlib import Path

from jsonschema import Draft202012Validator

HERE = Path(__file__).parent
SCHEMA = json.loads((HERE / "game-completed.schema.json").read_text())
SAMPLE = HERE / "samples" / "game-completed.json"

# Fields each CONSUMER placeholder reads (must remain required by the schema).
# ranking filters casual, non-abandoned games and scores Elo off the finishing order;
# analytics-workers key their projections on the room and its position in that room's log.
CONSUMER_REQUIRED = {
    "ranking": ["roomType", "isAbandoned", "finishingOrder", "cardPointTotals", "gameNumber"],
    "analytics-workers": ["roomId", "sequenceNumber", "gameNumber", "at"],
}


def main() -> int:
    if not SAMPLE.exists():
        print(f"FAIL: {SAMPLE} is missing — it is generated by room-gameplay's test suite.")
        print("      Run: CONTRACT_SAMPLE_REGENERATE=1 ./gradlew test  (in services/room-gameplay)")
        return 1

    producer_sample = json.loads(SAMPLE.read_text())
    errors = sorted(Draft202012Validator(SCHEMA).iter_errors(producer_sample), key=str)
    if errors:
        print("FAIL: producer sample does not conform to GameCompleted schema:")
        for e in errors:
            print(f"  - {e.message}")
        return 1
    print("OK: producer sample conforms to GameCompleted schema.")

    required = set(SCHEMA.get("required", []))
    ok = True
    for consumer, fields in CONSUMER_REQUIRED.items():
        missing = [f for f in fields if f not in required]
        if missing:
            ok = False
            print(f"FAIL: {consumer} depends on fields no longer required: {missing}")
        else:
            print(f"OK: {consumer} required fields are all present in the contract.")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
