---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBLaveAokJixfCSxHhCElERVT/yOZTFyTY3V0Cpy3Y0UUEIZCN/8iKxkCGU6DY0l9x6XRO0eIzysAh4580hqj8wU0uVlcBIoNtK8e1Unx5BnU0323GyhM1od77PmrxesUC5C4vZ1zdv31p5i/dZcu0Ti629meN0we37eMAyAyjjSNjIxvZc89B4CwZKQeSFYYR02smfnO/EJO6Mu9Nw1tKcbTdnWpJiez//dfDO7LlGt3Gvob/PCuaiQEOFIZyoNCfVh5uuZXofEWqKSajud9rOalwlSQfdrrEtKcFj5rhYWS/4gotKmCn6HkflrJgJCuhv8Z3524fZvitmFYWcsaOcboMTk+1Jj+NxFXlkzatwPAQp/sbyKmpDrDs2vWAdOo0gDxW8QZB+tKBnv+uUM+N0hkFOulgmp3UMoLN/LSA/3WwzWrmkSM+EVh7iu3UzIOV+xQCIXE/nXQ1oB3JYMuFKCj8vFIghpZwc7OX8DPRN2eaMg0SK5UG6ljtS5lY0u5IyW+upbqSJyc6hpY91fTxFYZMI64sHV8UvQgsEjJaFF7xHkTXuMh5WMZeqAiHZoeRnodP3Twr+cI3ZuZqtwkoLfY7IM78KSdnvOpJV7lNvhIiOi7mbJEjJ9SqIcD9cvkd84ddnm7tJZ2iUEGmuwtuM4diMtX9w+lzSWD8eGvKBUDQLpFHsi3R1CUX9pGBdOMulkj7z6wLtzIYZm7amSUrP0p6KoOizG3zz4aCxRW/4
    admin-user: AgBAIQob7Dg4IL4fEmuB14RuBfUJkd0Z0uQafn7Iupd7QpORsjVgN24Zudt7QBvueYw2FbFD9AN9zqGAVHwKCX/IothxjWYuZgM+hSrtZu6uusw/N4ZKBVucDLnHFX/srmIuXZbk7Ks5NJHwGGmYGF9F0lmGHWKY9aMG77yL6uqlywgvJq/dJE48vbTXQ1JWF6JyffzdMtZAfxB63lyGfBF7dBWChr3pQu1eNi1fj+WypZAKhPBbej5luQrzf3VIJsthe2h/hOvbces1HppUwPTjFAXfuw1zScoux8IzHA+PwEJ5BysmDlyypR3S39Wy+gkkndtan6O8AJPnL5qsBBOMliT9Xg+3yM1JbE56K5FAgNm4TMxLlkEHNIDDCbk+tY4VM/MkJRgfXjPiWK7SaCon8dNDX/lrp0+ZtJJEQ/MBTkEeYCCekjUHTFhq2WDJHvPqVlnss5nqhOiXbluUN6H+epr+KYMZQePbAnWyVsQwXg4rZRZZgyVjT1XVKRIyDXYat0aPoJyN4kMsRfc9iSWp6pLYpo7GINpHYu3OZlYS6FC0ioNwkRS035IGh2c5CsQKjiwRZx8TV7cRzTX92R2LY6UMCuhMDkPFr2Dc3QrgSENut0Gh8E7KL9VKYkaKi0FuPxDDG0P3tGzYsf9iXVr4Cwc5gFCWjYPljcwJS+FEjzxukmrVO15dEV1UWTP36oM3EFQTAw==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
