---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: analytics-db-role
  namespace: postgres
spec:
  encryptedData:
    password: AgBfoofYi0FBhQBcKWUQYapOMzjcqDTY7DoRPCujCpYDU6IZlDVFUFNuO2zV4YAxVOtTMC3VYeHjH1AScYaR3gtRK4dR+GypuMEzcTAFC6k2NXgJVo3/f0cJFbyxXKMPTKwjjjBVy/wkepx4uZXl42L9seFwpPBJ/uxklhVbug5uVgUHrQLCxcoeUMaEjBnxas7XxcvY30j+pUjI3b3M5qP23HKALSh/XtpdEw85HvCXNULwwQR1clHGRXAplIbPQrisdQvxJdx+N3ANDFtTeYa6xZVfzWSvLTMy0o82iqEKFaYrcDMJQJG7vClCILzJK7LgZj1Ba5SU+HX4MTRw63Hzr1u+O6rsha/cLNOaS+WplgK9L4+kpxbtXRS7YKvR3vmp6h4UJ2gqiW+KjbhpBd6xxVn+eA8zunbXz8cnTFBHST3zPNpf36Eo+gUfMOx8l9Fmxi+ybfshJa9kYd/C8BbWH+ZuyCRVmHHuzetz/2jl32m3UXSSiMbkPo+Xwe9UBeZSd1u4HrcodxRqrpM0MHfO7tx3xEDeup+vGY6NCc56liF5aI7A/QcFHUvCvKSqWNnQi6Dws557rqURev0LQxBVzZqJtj6bxBVq3vTtEWj9s9klBX6gcpi25sMl9OhsnCPBKE9Wse4VQ5mSbXTvd1+uGNhuaf7F3Vcw5+Rt+h8qG15Ed0KyzkgyT96IUsjweoH+52G7Xh+6Kf5jAo8eHANLR+W+LJ3CpOpipWGNHDcfzg==
    username: AgAO6HGDyHhYV0yc1+ZFcU4rUqRpTEa/JGJPIRnh9t5kxZWqGk4lX0ID6OIIEsnqcVqtUfPmU/BzLPay6E9Ns7Y5UWk4xjLOk2XjAefGD3A0+OsMNS19wemCZBqlsC6qXQHCcLs7kotye2c5XIu3Dbr342XV9wiYN4rtmfV7npweGn0VgPoFmjgbPABZl0PluKTvvBMKttKi0jRXCMNNF0vgOM+D1FECZcPVxV5Xund8+J9aZ4XG0zTGUnIkrdReol8OS9W91d6/xRy1tJcAjc56PT4RoHL+IlLsWX1sDW64WGEn9aRQA7EydA9kiHpTKEEiXiCjI6UA4PdQh6yURiK0tMKVh5yS15JEsfVrYkxXPAWSw9mWlb1+h4mblrGaeCIuqiLSMKkFguGND4rKY8jpP49wZYTG5VpThhb8Cdfsvwt8gXJvU/w2HFNJCJWUyCiq7jhAE7vygognFuoI+iQ27REzQPkje+0TmykSOBfWlohIH7ZBOZnT8SNPDVpSEyyx8G/aBepMeNi2aaZ141Su9nURQmSCUrsjHKUQHbmloCMA39TYsN4p2xRlxRSERcVBu2yaXAYY/nZ50wMRuG7k3OqoDyo29rIrDpqAWmhiJ1QViPKK1hl1tkIPV3wMDCFhvBR8TeApyskDG6gMPOuP/zJSEHGnAtYHENqmbpdmvw2QbrDXen49MQtxS783Y8BcMM0GCJhW0p4=
  template:
    metadata:
      name: analytics-db-role
      namespace: postgres
    type: kubernetes.io/basic-auth
