---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: identity-db-role
  namespace: postgres
spec:
  encryptedData:
    password: AgCIATgXHbDDzs2UORCTas227Lo6TQM85IzCZzJPjL2lxCrlkLdbuc/YfWbkXuBZQ+nQsRjUHNTHbzFfrVTzt8wkDlHkLt5c4kBHwJQu6XRYDIKmrjROXQi+aNyWlrBJea3hZ8JW9ELj6gsBUFGzO8dnePtkdQEyTViKfqVhFMEIvoVUbbmeenrouc6OjINFNH5JHQxuhdJtgSY6Pph3m0bw0R7zv4z3kM/xp0gTBP7YEAhdBlmOSLOaccnhoiopmRgK83TlgRal3YeBhRGStA7ve9cQ87gh0tot4uXNerAs5HFowFMh6BnyRAzIaB4nri4LQ0VSoRWMulLTp4ugzHVN+SO/Uv3p/zj+72MIWyRyfQDXF0AbvpflFn9nGeQfdVXBsiG3er4iXj2va0X9tfxDbMdBzF31QcMfsP/xz5Re2kw0a0tA5vfRVcMqWImktSlEN5p8ew1HR/STt+Cuu4FoRVgl4g1l+39s2LpUkrhu+K4j/L8iXmiDtAk3rPhdt2QkBFRv0uUc1/yrAkLyAMIyn2LB6YiP5+nlIIDNxCE6o2ITF6Xw9fMotpiSEn8TR0/ZDvArz13iEQih0StC8TYYoIEvQ4HvTRJKdrREkSZYpzO9JUT2rVjxGLcdCDmOBiQ7PFO+9qdrcVADvRM7N1VhIWaAtU+YA+HA3u14sJWS3HXdjUShdOtnnyq7eR10Ycs//bf/sAVwmDXsROOFOEsPsvhh1FB5BG3wQmq23QOmBg==
    username: AgCnSkk5XrlPO3DGwsRjVrKktCjnJM2KRQ5T/CkTrDAg5BuRboKods4XKbIA89rtzuuH6vsC1w0cXQuSsHNc9ruuXAYCNN9CFUiAHN8gMS7oRAdpga5mhQ/qlPsuvGZuVUmw6PFBsPFVzn6eqv2juzsRCfPg0aOzqTC+LatuwiuTmXqd+EV9cReSh6RukQjt5+Vr0YPKesOEbcy3bkB02MWpDXGJqBc7WZaeKQG/lhELmedeS3htIsKwCAY9LD/aOoC+KLs5jZvJ9DsoWmyLvje173qZuvqgHbaK6gUCAvgm9TkURrss2RK673O37snvN9gHbRXzXU/PkyuDUjtq66FEpnXjqZO//Icdxmvgw/WCFT4v+i1xDQkxUyc8nXFZSxDQd+y7dbf3yVurhX/OjmHxv3sJybKNKLpMsfs9xiovVAhlx1LMhLN8ZPnRj9iJDrH9lVqP3yRyPsfGq/kFV+AwQw2FV90YMKC5VBwfrWw06ZF2IXe7eJBM3qwzFerr5DoXgpLr0N4+hPnsDHCIr1/cY3T7cBeWrs8jXTFvJIeXODllfhv2pGKBUz5UgskQgbKlpoRlcPL0tGHtFhB9PTCsMZEHFnqyuhbq8YW7ivLWzalWp3pYfcH2dlVYmwAkrZ7YHRomxOeE2bNHbLyjDyRYo99+62B+aU26IOseJ9Jl06RBb1L8w51lLsZU74gU31piqT9/S3xdCw==
  template:
    metadata:
      name: identity-db-role
      namespace: postgres
    type: kubernetes.io/basic-auth
