---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: identity-db-role
  namespace: postgres
spec:
  encryptedData:
    password: AgBH2PV6lAUwTYaXo7AAHiDljkzaywd6J4PxxAq7Jf4Q60QbStiEuEzyCxfKI01TagCjhydnjUwcMiTb5JMIz4ikrEHXarzWz6fi2del3WCv5jQ2JLe+QZ7BHYG6/TuxAqLrik1Bhf2/vo8fBY5xB+QHPSNnHb2v741+qrPjCFC/xnBLELPtlEtS1cqSzLNUiRKRv270ZtpKasykBk1a9GVdTJZa5JKryf33MHsf5P7dT7za/fIScOJbCmhESSfI1uTzxiRL1+EexsIODqh+jgI6I7E9KFJ8Bpvv+A1n39zpUsRJyK1464IFcEfKA3SWGuos6+v3oQVjtUYTZPVk/giT277cHF6yP7TL8LQFnfiMfirAXMV88s2Gw+FJo3HnKwRB4cTUc5GJfAhJ0Uy/z1pkt/1P9IARodPaibgnB2wjiX+byBfSEXc235BN3hWRZUCOKeBWxOtLRP/HCN6dObZCfN6EYjkHHAIKWe7HGuHVh8CwA/xe4OST6Z27zFWI4j/GX951knband+9TmjLsyeg2Op6vJgi91mMhgiBYXeE0tS5tlcSvlTJ3KMYqBrG5nFWqasem440RTUsi7CtIHKMCmTCak2SbLNsEBcNl/7yfuF38AhCtnMnbWaHr65JFJ9u8XMFQTQrIrG23Xh6oc29/10juDucVkkQqGf7DmJL3KXKdflHeDSUO6eRiaKtIHJAuVihssGsb7p7MGKcVqgvGLw2gEt2prAlZT/Faaojzw==
    username: AgCaeiNg7FWpJZYv/epBSIhCf9N0UhlMYtf6shjMfQNhipFo0ahjySnbcCCFY2sItKkOBzKJd7RnYTzT42i75L/snBaMdSStXxvXszedXo7IHYIhShWs3raEBBxerEfy5SUf88egaKwwfhwsAMuwO/g13kfM4KLv8bE4KZMz94DEdCGN6hpNge1F/gA0baUJX2HkHzllofXdRg391P3IcczHRXTySDWSbnhrLkUeyjD5Kdo1QjL74Q+mX2xBk9RGE9wu4ffsIyu2mkykeSiF+4ONq4Io8d7BwnqD4kZ+yBhElJJ3IrWlZCGS5cRkCoG5PwtHttd+VXagZNrEQ5X7mTPsVPIG78ZmuBkDARhCnGqBZscjlazzzVlfnDKNhzC03uNZrBDjo5aiU3lI6g+JTOOSkDL+yTS/F09yZ6Lfyw/Cu2MG7fMWw8W+aQMn38NHuR0pzpL9imoj6vv7rjwVsigMKZwsEzdCKCDmrjcWyMzsUweWN2nEghMHs4mV69HSsFTLayh7LMcSTHhP+R/aJXLqdM1LtWVlqhQE0LqaT9xGlYKmmwklXmdLTuhkjJBrPuTO1yX424iNrAALW4fMFJeiTWI1/d31Fac0Q8R9swHPoRwaSm7R3JvVtAjZj7xnhkF1G84fqnqrWp1n+0VNNhQi2u0YDtfUe31fzcTOK5660ixH59URtl/PdHgyGjSfFU+Fo4DLiXLGCA==
  template:
    metadata:
      name: identity-db-role
      namespace: postgres
    type: kubernetes.io/basic-auth
