---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ranking-db-role
  namespace: postgres
spec:
  encryptedData:
    password: AgBnBNcvtmCxyq278WJUYWgUSD1myMX/TsxndHNjFfGi5jvDa5+2Q2k5ziopOm+H1phJqkIcy1x7L5MjOnlQlvBsbbg39SLtge0FtAPBfEZMlv7hlAqt4Ea/ndQ+NLftcYOfDRoF0VCzdYvh5f12OmvLxI7dgglhHF7RGepP/TauJTSe9FBnmh/oAGp7ejt4uxHMzocnHKjVdh3JuJEkugZ0i/8Rm7FaEMBpTPLtAVhrIZW8S7a/zkRi1rtduxPnjlWJ+5dCp0zvTHsI4ZGw044zDMJxiZOOTDBX91AEqqgS8Mjdjuxba80q935++Km6yrCJSYX0yFGMfJJUgCUz0SHdtyvPctiAbuZLhIYVlcZ+ywnNgrkjXakcXuKYpahmVcdHW03LZPoO40VCr7Q4IH4rjj/IG0JvNbYr2sgR10Z+F+n3RmIuBQjCFEp3gBJxsVxPPxIK5qVBCCS1sjtUYSlhMQew05enKmXZGQ5dbjJr5SzEhe4f7sHO5xwDd3SH873hOcfFMMGmp5uJJ6HHmsLbZS/r/z6MBig5lEHTmNxNusSY/72OcrL+wdtzbpgijIjPfVDI0fs2wBS/TlNLEiY9oCpqAQmq5HJLECCH0g57wcwWZCmhYLJRGsu6BIG7g0gBMc3VeASRqQacOFGjamXcuRk/piViQKw4xLGToxfiaT8uuMlJLJUAIreffli5zYf/hP4OnTtiwxxPzd10ZSgIyKaN/uq01AyrJvnr3v7R
    username: AgCnGwBmF8zQDZPaOuS9CJCWvQx42r/2mRpxDRt2J4UTpdo8Zl9vG2QfdAN9o/A0V9boBiOqLDU/uteR1d91w8XEycsn0L6kqkOE1WoQ7iWVL3MpOYIuivIhXfq7u8PdQX5PrJNUgLzaqrHzqVunKXfqrXqXKndLWsFKUqf5KhhFSSMhSHK4VkAvPktvaKEXHuxqn1FRjXPvh5K8p4CVYUiiSNNovftKmiPKCukNptba6GJMO3z88tZYiwzT5B2DmbfCa9xu7rfUUTvKPj626fAunPUPeFDqdBwSqjPJ0nvVKbp7sL+Z9jdGxnZsPhJlFddIoq+BebKXGK0bn1DIhwTM8jslfmOxBXGbieUXFRaSoRDxzbZUGL+1hoHiFb6pwL2msNlP5yc2f7y48oVD4t/hpES7MGXz9dgVGj+00llXKZLzTHTPX1XuE0Z4t8dfabGF+2BnjuSdTXrYVk+3rYhXzErR4kEFnR2JUFq2TKBBWpuethzh17rLGgEg+n2FgAalvYczdaPGWRr0FQOr+qnnhkOQE535EwpR0cUjLODi3fUDein8zdp2ntewek9LxXoZcvRxe0XZKda831qLxEZqrzMHkPOpcJ7bOxH101glIUyOASfv/H45ZzUSrDN6mXxv7O3u6QuKVuq4scHa7RMCceOTs8gOSTVJ+knW5+Um6bCkNA8vIeuRjRiwdSMJFu+lJ8NhnO2k
  template:
    metadata:
      name: ranking-db-role
      namespace: postgres
    type: kubernetes.io/basic-auth
