---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: room-gameplay-db-role
  namespace: postgres
spec:
  encryptedData:
    password: AgBTPZuhtN2ZncmKPCV+Kl8CPNDBt/4XG9o6vuetJap0cHYjCquY6JchHr6ycfa2tSYk2+Cc1kW6yo5jFtiME2S4i7gMqF8q2DLwFeFTPhClt5YQYx3xazyO0rzWTj/eOWhuFCshgyiNU753n6nPnjMvGRfruClBoO0VhfEn6NL29AZ7g1WS3qkkuRLuPSGFL27oJBeBb610Kmda7LcNWsz/fKLbKitXay08vBh04Rxtmse3MCeiLjiTPs7OPPAy30TSmqahWUpTF6ui4f9w/D1S7j/bUZtF7YjPCBRhs8ppxtGwo3+6ntCSl571OjrquiQvMeWRj+zA/Kl3+YhQvgFmna0pZLsXdDg7qdhlvltxJnlg/c3dsQo6QlRO93qFQICXMU8MZZH1zulbOaNBsxObLTvTTYVnP/jBLc6TsLgLGUf8gWSuNQjFzo6/kBHW4HWl4HcZr4fXDvOFpv3hen6x+fri6nzehxpLs2KQrrSy+IPxrBuS+mU42PzjQaH1FI/al7yWo4gpPyV4rLnQgZl+vU8A3QCqCMYJFIHDTEKnRE/Dn3oUH2/K7rbu9HOLWzpW/NaaX8hmB2YX6sw48muYf7DFmwbs1Ls4HdJkoqJvIrMISn9/9yAvgrs5gFcxalYIll9n2sDtqtruvMhm2osdx6Ot1KcMtb7UY+o3LUgQ0bi3AltPM5o3MujLi0HQi3zGkIskIqe87+jLV1XFzICCG/TVDOM6nATV6g8MZM+g9g==
    username: AgChX6SV1txB5LVyhZkiTN+BvIQWVe6rWEq69q8hK2FwAQlwNDhyF+2YB07fQkt1joBNSmDy+/4e5V4XR75tR7kG/pNGtg+dgHNVPwQe3GhX0lm3zm3FNiE9vt/2GPrnNdBHYsST/7kyKzkMhvg7DJwgZgwCPx80USMLjrQs4/0cvSt8c1r8Uco1ogMJlXBbbW9Otni8vaKd26fFY2nx794IvAln4syeiGX34L2fIe4IB2a/61Et84zMbYHlQJN4aam4dD63uYKE08+FWR8NRBMpVOl+ylki5CYJ3q108qUMyjPiEym2EoRR3TOviTKsiQBHQY1YC6ZUyoBzBHq9K7APIhz0j5SRpXfU2ANXgTuSQLvQDm8xoHEbnYxMUI4dE/p+5MyQMuQ1g+Ux9LCanjpMewHYY3vlu0pMylystnboF8i0E6Qj5KhFc+Xuf3O2rjpiGz3dZxvUlXlqlORSmLQoXYmv/pKuJMPHkLw1iqAzJDbskspE27f+ieUorSPPzzRTWvtxOUuOmI/1QEWWI0ecC6JzGpBe6L7SGfpSSSLtr5nV6XceOXK4Eb3PGnU3+KgThtZWk+OYcZJ+LqoT6XrrPtroBR2xfQcY/Hwaz10UuY1kKHvUj4czNbmhOLIvpgSLKa3ft6BW6srlOAjFOkwEJSH3O/fOMfmSYC1cmI7aexmzwpD8if6HWuCOTMjDwWOnQwcUo9GtOEFWISM0
  template:
    metadata:
      name: room-gameplay-db-role
      namespace: postgres
    type: kubernetes.io/basic-auth
