---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tournament-db-role
  namespace: postgres
spec:
  encryptedData:
    password: AgC82dxzClhrTnLSueT8jIiIJGCqhPrHn1PaTk2fN2BEKJsMSBjSodEG3A/7E+3+AlMbyUAkoLtnAHDf0pdzgQPPcUbkP6D9IFPlCBnBIUjPokn/GzVTH07Ro6P77ijRI0cwJCY81WJkErDoGIzEgngnehojv0HnB19XmEf92ERLjTpGKCVzpSYnIypSdtbCH4wAr02VMNrjSft1Xvw7ObR5xwQbRZXFveTkULTISniLya7jlnFl3MznlYcbW9Ob7nyrP5mPKBYJS7K0jM9YLnCZUokO8RFQ0hIM2zoREawij5orHjA4HX37zBLHBrl49aoY0T6jYH5PzJgOgRyAca+UlxoulK+xFd2vl4f/+xiPGRhksD+vdJWEhKJzhd63w66vVrwe2J9Lu8BEVR3Iz6DXK2jof3S7TrsUgsru3T91P9goL6bI5BE31tW4ijDB6DEDpOuV5in9/VHSmb45qsOCGv80MI/O+2je4r4b6SzPQwILBZYNgdAyMo0k1AxUVgF5nyoLXj+EcddLbjjAyce1tXn93YsBPdv8q7Ti9pltasUxG/Xe0T2t8Qo+SU6prGtuykh97Hym8qzPqLGo7LF11Fd1q10NjYw09VYC/TqmCIAEiC41c/j+NSMo1vQdQijqQz2iZRI/c49f9dQ+Tn/1PbnYspNmQZ1t9I6IOYAnoQT50zoiPHKjaumA9srJN89vd//OrCxRDiJc0qxq9s7DWIVbEmvHVDt0NYTr0w==
    username: AgAV9boFTgl3+oqYV0aEdKuylxnwNagnG1O9CQTQoteQ5GMQ4p+lBxVP/sjOrZBTrwO/wQyKQVKXBKndzChTgu4sCfM8mv8nh0Y6xpoXS/HDJauavW8GAw646Ktk8dozoIWsnkiE7PClPV+/MM4ICKX3YPA1D7rAPJvCc9mvB63mk/bSf9eQN11CZ17ewxmOeK5LnpVrtcT8onLsRXmjLr+Xp7VwCrPg0KrO9JcYJFSXkUDfPuEBgRjicbZoDLvHy26VnGXluPz0TstMAdxvk74rUH40yD7iXveLmhaX/Ui99hbJ6E3jQrXrwIKodEjTrsZ4AUHHbFcsalB+xiLmLIKBdgKeujfSVAd54kICYWgslp4A7oJ7obixOZ1jlpGDVTF24n319eqnjQZrdqhBmdp2eS+UrN4lNNn1xxc2ZNeT0uf/tIBItyeKf4pEkGsSy10cp19ZfJBjLNNdIm0NSlCWbLxnw6zd+Y7MinKU4VX5ilLWwYIwZOxS5HgsGEjGc8+YhBzQLE8R49UH9cTVs6DMuo/5WUMZMl4R9uG6HlKudjkoOJd558F8DD2AAAoEjBUI21lK2YFGENXfTu/tFtk3UA4RfjW/INpF3eK9i61U7roQZ2BjuVQESaqPxDfQpNld+1pC+hNmpwhjzdfad7wfsPTLgeJ1jouiEIB7DFvH/qXPxzyobkoCADgslTZCN9eSBQwefa518uTR
  template:
    metadata:
      name: tournament-db-role
      namespace: postgres
    type: kubernetes.io/basic-auth
