---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: analytics-secrets
  namespace: unoarena-staging
spec:
  encryptedData:
    ANALYTICS_DB_PASSWORD: AgCafvG9UrhqacDhKoXKuLzPffYlGGU+dJwY/aXhxWxfTBpy4U71SoYLQ8Ouz8iSYsYfhUOxxdsAcC4QiwvLoCFmpnpWyUnAVIMtICyhuxNGuSQPIIWdTwISoEP/rGlKr+WcS5/NsJE8AzxaRyo9UTXp1sPu88jphcb8UN3faVrc19GpajLmkseK6Q82uel2b43FVFZvtD8Yz9TF1SpEO2p/mQWQbQNh4jva5pks/Jsm+B0TSAUKKi3nS3BCejL2h9ugvL/tKxfKit7R2jrOR5Bl2xE0ubNu40TUtalE9uX8h/0n+a25Cll9QJWL1+Dja8VvVb2MCEyPq2VRhUqvn96DdGQpN04Hwlb1cwezmP7KAOZRCD8kblzzXIxAeTdBTxMq0GbmrinG0b4i23Xx2dwiz6tqJ3vw8HF7B2hY6ODRn1E0wwe3ROMVG9kzd4/HozflF/6uH8/xVyTuhRCRfY6mNAjUdz4BBld22zTsfne5z10MlduhAOwtBB4qQMNWIqmBs5+O0KLd1Dlue0zhk/LGJJMI6xFm+3GG5KYA1xq/KO2YsIitXW30tnpkwC/tNQK7iQ7JP2L90eLVYJ2K7iU900FUgApKgPz2v/9vufjisS16I9PItN0gCR7RjwJP0BG0V6sWXg5AbX/CTe/4Ysn1lFUStMFAU/5p6BJ1/qkXEpch2nbexE3WG/QbjnB5K3Te55eIExd5bQeFDomfGMEM6pFxAHuHnXGlG0sjTY+QYg==
  template:
    metadata:
      name: analytics-secrets
      namespace: unoarena-staging
