---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gateway-secrets
  namespace: unoarena-staging
spec:
  encryptedData:
    IDENTITY_JWT_SECRET: AgAFDIGS5OiRVCjtk9ZC8uusJn5foYfggMEzY7NnOW4dU4WdLGXmzidFvo7ZIUlkyVh9k7MHtfutkeqZtSYXQdtW1DtDQV/VSDk9aTItsYiZjMtNBKBoIqWU/6LcEUYvyXmTiGrVYl37yb9Q6B4ODP7i+RYUYqkmu9cMZw8G35cfgmNgDHrOQ5DqZ0AYd1iRHZ8t871Q9ZxD4160sSoe0jBRGIhMoHNabJ5gYqPCmksEL+7W/2bGwBmnnNsPiUUQO6NCVS76bOpU22Mv9+9i7M9GPo5y2CfUwk1iP8Lsq9tfBJ4pnZPCz9kdSj+MyBUl5dwGAouVhhjckAluVaad+/vKcMNF41uTXCIItw6JxDmrJFPG8oeBCaw8GBdhKk/SeIYZjq7YfGNwBKBuRw/yWyn1hDeYSv0ye9Eqqhy8y9OfIHOXoatWCVXOjrYImj1ZVoOe++AO+BwxSl08iwx7Pd+veb1SgJ3hhjD3Vxt9XzzlaIv5CEhHGenAc9Gh0HLKR/8we5GsgKOiRgUaR7RnP/U+KFiHyWDLZiysS/pl76bs7K2ZVgJT3FD2+9fHRsMBKDaanU3Pcio6zjk2T7sanJV/OLYAqShpXabb52ZGnl+eULXfCfbwEy5OTD07t84OxsOzYLBXNKalKpwMHydPdlD0zmLZFh7OpTqeUsyrZrTJdZUDJS6rkQ0MES5pj/ZO9pUMxz0XMuEWG9DEa3tBFhT1T4t3dEXe+xD4R88zInqADmtNr6299h0rfg==
  template:
    metadata:
      name: gateway-secrets
      namespace: unoarena-staging
