---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ranking-secrets
  namespace: unoarena-staging
spec:
  encryptedData:
    RANKING_DB_PASSWORD: AgDIogFgoStW6ufHz2k0NsZUHVoV96uKzPM1v+m3psnCxPhajERg2dmyVVA5n1FPNAxYuOXZrozMb2SVHZOOn4igJyTSao55krRnvwAgPHgk3AoUP6rrskSU6OXmvpe5nCf/iUVaOcn/lFHRstrL0mc20jzoE6jCcuPvf0k3ulMHzrGEECtm7Ti+cv+lc03dQW1QpFQ21kZxFK6tpPecKBEh1yhcMsaoQLB1hcgysaOcmv9bRmh8MCTuszd31nxG75W+APb2UPv6JtRllNV0VS8uq9yPZ8KlWVAA6vFJMffwZ7AWYqJ8sHydIPj0SZvXAannXE1mS0J1CezAywM/38f1TRNBx4CTkZC6M6Gxcb6IXbumGSvWxThhvtVrVr2TxKgtmUHzKPfufq5NUvvF1kRcQBJaYG1fQGEUuIgwrDp63QQnu8SMeYLV2ZIPylxy92qL6rUdzbS8xhUFnrPNTfXBLo2sy+7OzyTGC0TrYeBpHZp0xAvBJ+mw03VyryF8HQlCQLT0ad3VTWjH6OP7krBPobe2X2Pjfo9MvteCqSHFtwSwuUqh8Rl7SUFqEuvF6+F7l6q2wutZR+SigIM0TtTJJBwjumXx3ntvWi9dI35g4OQ5pCrTwVCmuAYCjSqsruOYlMDn6CQCHSsJSiBL1cYlSRoTh9Ju/IPGnC2EnuOmnF4AWmmizHTEOOSbdM0utsChF/CHS4I0/mwpXPWgN6/Q6M8uHeUH9+VkiaqiPDQK
  template:
    metadata:
      name: ranking-secrets
      namespace: unoarena-staging
