---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-registry
  namespace: unoarena-staging
spec:
  encryptedData:
    .dockerconfigjson: AgB7nmc1lakNIbMF34Wteq37lGYwaVNgnccGp6C0LJeiusXqTuOd3t5VF2zbfusR7XV0bu0tTseJBYEban2rweRgftehDCwJCh+I9zPy7DSzBLs9IDYtcoZUy24BBlCQCHguJlXcnBKiS8Uo0kXJgUti98Q9shKab6QFAYNWv9IyvaoQpDeuD5aNNUbJRaTGL+wQn47gvVKhHEDV8vsuInbIol3voSTqsfmD9QMxIx6FA9E/v2MQOIzMmDP813d2Ea0dYXu0RcMHH4+UfT6tLNBERkInDjqTj2mf4PMfPxPQINGmoOIW86irZXcZNCGku99uK+3g1C8iPKKSdo4gKb02UvM6MsFUK4FZi/grKEbkaaagoh5GyDS2IqXZ2cTo41BzkHRcgbhWCsKGQZuMHWNXut/dubXhijLyDay7FnD+MPNrSMg3kWhOZpB4H494UOWqx1M8grt4/Jspb0uQU4zYaY2O+CbdlmM+n2apzMDuZydmgrGxLov90qd3Ic10fnsQ2x0DACi7MnSk/YiEbaCn3BIaHSM8kY2K0Ss6beJeHe5fZTPL2A89DLpxcTG2JSQZqiUdHEh1JFA+S39Kp3ga+lueOp8rgaBXMkGOl8ZyWf44EgxT3CZxw3gzY47nWKqEWsuCON7/c61mpeGm09gwOp4h2mmE6Stcsbmkb3bWmh3yuEM4ouxv00M/3sIwkt2cFLmDsMriN87zhbgIbL/KLfyVmZwc0fOJ2AT3jdwf237+0+4O9PWRqcm5eTw7wynSi/p3wf79YRlLhaouWtVSgkaOV64eQUNGOH2CYazl+u20EiT6uDCFI1s324uBcdXAuXJqFp+xOeoM5i/iYwlW9aS2bscVUsJ8gR62F/ZL1lRXT3/Ycqlikr+yQi/PmydL98XDkuwTUCKlzmcHkK7g2Qz0oIffjCoAaU2z05vq
  template:
    metadata:
      name: gitlab-registry
      namespace: unoarena-staging
    type: kubernetes.io/dockerconfigjson
