---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: room-gameplay-secrets
  namespace: unoarena-staging
spec:
  encryptedData:
    ROOM_GAMEPLAY_DB_PASSWORD: AgAnpxlbRr9mnDSNVny0xQ/dwDsUBD1bV8bIWILz3FSwzH890ugaahl+IyyT+CWNV8BRgCOLWiSiZSO5yT7kux0q7fb/tl0FGh/zXHI75hixNpTpTrBedr0c92lHFvO5HklNLcONEKtfagicd/U4OaIluSelBlItHm9z3ThyFlBqg8LNnDiwctrydX8zHlLP3W8Fjtwt/KQvbYyOMmSiOFeUW5xx9xwtgAgOBd3PNW5X4w/gMSJQGA6PFuo3rs5r3U8HXIkpFzSOe6hdcGpOuhDzjAVTRDY0fRBv02DIhDYQERnbdwJSj1KucYfwxzVXr7fGeG1TmjhkaqBLi2VM7zmTuhlH2OvjoMgGDgtsDBJiJVbpN5bT5fe8UphxBgKMsNRuCgEqOK96JTI7FPtqxlvtol4WXfC6dQ18C2aoetztbLm9wJC7OaAJiQJFOrgLHRV0l4qUnZO7ouoBBGFbk5Lu4VNwYDajGgeZahkW1Dpy2ib17LQHuN+I6jOfZm+NDwvftm5/4/Qh3PRf00k12OGXcD/oZTtLIN4M1nck3n4yPRx+f28r7KWEBCWoZYY/lDm2wuOeydsEDVOaCmzvtC/4N15kgGmk02DuLeS6X5Yj3BkspOPh6eUvQuclz/rFHQakV2ty71d52tHfSVO+TWfjZDe6/KT8IU349uA4q8/INtFAzFvju16bBWAOyQwGJAXlgLmygO12u/ri/cj2v1U2+lhr2khG1W8juhxvqKy6CA==
  template:
    metadata:
      name: room-gameplay-secrets
      namespace: unoarena-staging
