---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tournament-secrets
  namespace: unoarena-staging
spec:
  encryptedData:
    INTERNAL_TOKEN: AgCSY9zluwFfN6vrLqfYBjz2wkiAMpmtfMty/NodH1Lw3kgLp5T9L9SlCI5S3eYBO88AziMl/OxOxbT6QQoL0cbF4QYbTxyTIoEFfQD3sNzNBU/eBByL81bLD/n+nG1vvMFBkacTo9c1uk7eeIY3x0cwsZewfe2OmP6BuZ+MpVYBGKVpQ1edKQvmYrX+jmNtIgcV014DtMGrtJMvXx8DEQ/qIX0fVjdke2g15N8hKi0P6dQan9zh8EMeGd2XpJb8bB8k1qtJ8uurL1e0woYLc61gkojmpd+VqI10uTHDS6tfYydl3vAvZ98WmACji6mEnNEh9qJAZT/HNoe2VrQqFsLWtKjhfRaQWZTdd5DP0R7LSLKU19GqABqOx2zIdMdRezJAGYzW0cTCgyoGRv9F+3O4m0RC8ZYUCIqJ1qWZBZEyF70xMOBLIfC1rqouWtBiu9yvFCmKdVgpYwY+9J5bO1UdBw9xjdCAKZuGIjUQ8K9R/R+FUxrs6bwOkpYPe94hyYCMdTqOFkAQ5H01YucHyYXusgJLz37GPPgHpqtGf8o94mBkqY0U98EKMdA239uo5Bg5jUmEgFlxVOHiLC2vU8qXE7awkXEv5XGh0oVByOTsxu4olXjxb9NxVPRiZxUElNkRqRrfYd8F0USub7SAgI8NpWy8gi4Vhp++21cjHijKlnHQseqmCiPSERiio1Zc/aokui6Fd8Gp5JDzWT5ZhWt13DAv2B0iWDgNJBc5Yy+uoKYfq4anoirMJg==
    TOURNAMENT_DB_PASSWORD: AgDVthyEmM0zA3C5nR5uqspKLIYi8APSfNX6RuV6vsoaChpuB8r1nb6pjaUpqovzGZQLa58tu+ZhWY0YM3/7L7KZWwfaDHLDurFTMdXiIZxTs4bH/+HGAs+ecbrnbjESftosjeU+tK9m9BNReyZCvBimww8IoVNxxqV1H3aWFwfgJT6CdrM0mndbVyg/IZ+7XmTKY/IV32nGZPsf7wxDCBg7h9DLxVbvcXXu45hFmXTeylI53RY1juDt+s0Og1INFg2pIiJrzaz+ZGYNwoVPMVfAXgS02JQY8JdTRq8GFe+xS+J/K71oGT8yDV81aqcn84QNDla4ZQLcohm067o4nL26gK94tmD0Y1CduVMHAjWMSa3LwptFIac1FoUQOZskp3dQAoMpmuSsz3HLLifYgck+dWwVxsp9F+hLloW0VjmnYXAQEdJ/sOXW15yhnI/pNu8+tEvl5Wbs4NBz7yrLr9oUDtnkaGkYqOyC4xZ7MKakbaqg+wB25ofXxk8B+/q3Pq/d3w8CAP25BW0vECvAKRaoM39CBikMNm1GnqCELzZE491QONNczgOQrQqqAcUk9ORA+zhMU/7N0B60VNHQRew7ZY/NW18x2rIIQ6Pi1X0YWuft7mqwFUt8hUgCGVUQD5q3oB1iUKopOfg00utW1DHE3IGbfHP75yWX30PjFE7RFShPAq0PlBGctdGDqSpA0iu0EgW9rk6uU0+csEYeD4ASSCAsNRhCsH+CrVTCZA==
  template:
    metadata:
      name: tournament-secrets
      namespace: unoarena-staging
