---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tournament-secrets
  namespace: unoarena-staging
spec:
  encryptedData:
    TOURNAMENT_DB_PASSWORD: AgAGLajSLyU0+OJ9KHzY9g8XcfMEQZZPQ9BGU/HIYTYt2SQL8P44y21RVPpU+x7ChV+dOUHlFy/3JGWl0wy0PckMobZ1ZreGgMm0faBti7fc3SdR20RY1cF4/kUwSVI3Ci1jnRVANMimKkOlyCn44+zq9wMuyGW2QFL/2s2q0enkb5HYW6okTFSO/djFMwe3dnSl6pxayrmLPaHF+SJ0Xwyn7ehpiVRIca9sYRC9Kk9CPCbP/bzNuL6FPyBTiOcCzmVWbKJxYsS6eta24BZDT1mM1sl8t/KCFQvJx19FTD+biOP9nLKU4kzmc+Vd36H0LG9a4T7DK63M4l9CgYh5jnxkXMgsX5pe0m6OsudLP7CDtVes/yhsF0T+PWnrt8A+UrkPdfzyk0jVM5hxdXxGJOU/l3OQ4uM7pgYNH7U0eAY2BDD0hxapGrbEBWChet2tmWLJQ+KXSn9iGrAkAYXwPkZyIxQWsYiUfhN0e1jCs/W2IUMm4HQ9Z+HD1XtDdjPlDTPvl7+RL9FiygmXR3kYpIQ5GTObT818gOewPa7PthMb81G3yiE9U1XEUvl7RE8C9mR2r5YIIATwveX3eizJNLnZLrGUlb8YbDDtIRgTXKqWdBeihc2vPkdKUiAfE9aSX4XTJUPiXZs/O8inA74IXOBYeOUkI8N1Lke5IuyOGgb/ok0zwtMFFp0PW+tU/EDPFmQAIdMafVQKpz8dcqQb5RmTMNCbX9Wn0wobPaLimQ==
  template:
    metadata:
      name: tournament-secrets
      namespace: unoarena-staging
